version: '3'

services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    environment:
      - "DOMAIN_NAME=$DOMAIN_NAME"
    ports:
      - "443:443"
    networks:
      - internal

    volumes:
      - type: bind
        source: "$VOLUMEDIR/wordpress"
        target: /var/www/html

      - type: bind
        source: "$VOLUMEDIR/adminer"
        target: /var/www/adminer

    # nginx매핑은 wordpress가 먼저.
    depends_on:
      - wordpress
      - resume
      - adminer
      - preswot

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    env_file:
      - .env
    environment:
      - "DB_NAME=$DB_NAME"
      - "DB_USER=$DB_USER"
      - "DB_PASSWORD=$DB_PASSWORD"
      - "DB_HOST=$DB_HOST"
      - "REDIS_DATABASE=$REDIS_DATABASE"
      - "REDIS_HOST=$REDIS_HOST"
      - "REDIS_PORT=$REDIS_PORT"
    networks:
      - internal
    volumes:
      - type: bind
        source: "$VOLUMEDIR/wordpress"
        target: /var/www/html

    depends_on:
      - mariadb
      - redis

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    environment:
      - "DB_USER=$DB_USER"
      - "DB_PASSWORD=$DB_PASSWORD"
      - "DB_ADMIN=$DB_ADMIN"
      - "DB_ADMIN_PASSWORD=$DB_ADMIN_PASSWORD"
    networks:
      - internal
    volumes:
      - type: bind
        source: "$VOLUMEDIR/wordpress-db"
        target: /var/lib/mysql

  #bonuses
  resume:
    container_name: resume
    build: ./requirements/bonus/resume
    networks:
      - internal

  redis:
    container_name: redis
    build: ./requirements/bonus/redis
    networks:
      - internal

  vsftpd:
    container_name: vsftpd
    build: ./requirements/bonus/ftp
    ports:
      - "21:21"
      - "10090-10100:10090-10100"
    volumes:
      - type: bind
        source: "$VOLUMEDIR/wordpress"
        target: /home/vsftpd/myukang

    environment:
      - "FTP_USER=$FTP_USER"
      - "FTP_PASS=$FTP_PASS"

  adminer:
    container_name: adminer
    build: ./requirements/bonus/adminer
    networks:
      - internal
    volumes:
      - type: bind
        source: "$VOLUMEDIR/adminer"
        target: /var/www/adminer

  preswot:
    container_name: preswot
    build: ./requirements/bonus/preswot
    ports:
      - "4000:4000"
    networks:
      - internal
    environment:
      - "COOKIE_SECRET=$COOKIE_SECRET"
      - "DBIP=$DBIP"
      - "DBPORT=$DBPORT"
      - "DBUSER=$DBUSER"
      - "DBNAME=$DBNAME"
      - "DBTYPE=$DBTYPE"
    volumes:
      - type: bind
        source: "$VOLUMEDIR/preswot"
        target: /var/www/preswot

#기본적으로 컨테이너간 통신은 도커 bridge 네트워크를 사용한다.
networks:
  internal:
