<?php
/** MySQL database name */
define( 'DB_NAME', getenv('WP_DB_NAME') );

/** MySQL database username */
define( 'DB_USER', getenv('DB_USER') );

/** MySQL database password */
define( 'DB_PASSWORD', getenv('DB_PASSWORD') );

/** MySQL hostname */
define( 'DB_HOST', getenv('DB_HOST') );


/** Database Charset to use in creating database tables. */
define( 'DB_CHARSET', 'utf8mb4' );

/** The Database Collate type. Don't change this if in doubt. */
define( 'DB_COLLATE', '' );

//redis
define('WP_REDIS_HOST', getenv('REDIS_HOST'));
define('WP_REDIS_DATABASE', getenv('REDIS_DATABASE'));
define('WP_RESID_PREFIX', getenv('REDIS_PREFIX'));
define('WP_REDIS_PORT', getenv('REDIS_PORT'));

/**#@+
 * Authentication Unique Keys and Salts.
 *
 * Change these to different unique phrases!
 * You can generate these using the {@link https://api.wordpress.org/secret-key/1.1/salt/ WordPress.org secret-key service}
 * You can change these at any point in time to invalidate all existing cookies. This will force all users to have to log in again.
 *
 * @since 2.6.0
 */
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
# https://api.wordpress.org/secret-key/1.1/salt
# these key are generated by the above link
# and then copied here
# these keys should not be exposed to public in production
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
define('AUTH_KEY',         ')kZM|bx6F]e*o1ogaN`fV1=yakEK39pb/l36~8[-=x%y-:s@vcm5a_=%0mZSk=,J');
define('SECURE_AUTH_KEY',  '1[$n>Pq3-^yHzZ.X!Mtj!|=&AU+B^{&N?<|$=Uw7vdeFU]RJ1b!jQ~V.tf+[S/UM');
define('LOGGED_IN_KEY',    'n?&O .|EV&|Dfx2ZBQo);#AV%j%xN.$H_Ay+` B6S?mGr^b-c-P71{H(DhE]--}J');
define('NONCE_KEY',        'ec]-W-op+FH[P20_h$,L%6OB]*O.+rvY75`1wJXbY(?7$^n9E6uA&e0Jq7_mGU%R');
define('AUTH_SALT',        'C|<8_D;Dq[Sh+sOhvgOl/3sOu4n=UT*`hVwF$bcOzFr7Z (Hu#B[[,KNVo{0((ZT');
define('SECURE_AUTH_SALT', '+ScW6(zL0r9JIj(Jc)-p[lpZe+F83EM0[>Gsqy ]$LU{,;NW#-%| S>X;VKQ>$N(');
define('LOGGED_IN_SALT',   'S/M(P UydfJ9||b9yk;]mh)Uq;}M<pl0B8=)%Yb9<lW?=G/X8ymG.u8jl}qL^sa$');
define('NONCE_SALT',       '|Bt{L 8*.VOwJi{w@dS4!SZyn4An9CeI10xyA*A=~4sQ+5>~gk;BZ:+mQ_E[4Z)v');

$table_prefix = 'wp_';

/** Absolute path to the WordPress directory. */
if ( ! defined( 'ABSPATH' ) ) {
    define( 'ABSPATH', __DIR__ . '/' );
}

/** Sets up WordPress vars and included files. */
require_once ABSPATH . 'wp-settings.php';
